name: deploy to server

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    environment: main
    steps:
    - uses: actions/checkout@v1
    - name: echos
      run: |
        echo REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        echo REMOTE_USER: ${{ secrets.REMOTE_USER }}
        echo REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        echo TARGET: ${{ secrets.REMOTE_TARGET }}
      
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SOURCE: "server_node/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
